### ISSUE TITLE
Exception sending to Sentry from Nuxt server on AWS Lambda

### ISSUE THREAD

**Issue by charles-brett** [nuxt-community/sentry-module#320]
I'm having an issue where my server is failing to send exceptions to Sentry from within Apollo Error Link, but only when hosted on AWS Lambda. It works if I run locally. Details below.

### Version
@nuxtjs/sentry: 5.0.3
nuxt: 2.15.4

### Sentry configuration
```
sentry: {
    dsn: process.env.SENTRY_DSN,
    clientIntegrations: {
      ExtraErrorData: {
        depth: 20
      }
    },
    tracing: {
      tracesSampleRate: 0.2,
      vueOptions: {
        tracing: true,
        tracingOptions: {
          hooks: [ 'mount', 'update' ],
          timeout: 2000,
          trackComponents: true
        }
      },
      browserOptions: {}
    },
    serverIntegrations: {
      ExtraErrorData: {
        depth: 20
      }
    },
    disableServerSide: false,
    config: {
      normalizeDepth: 21
    },
    environment: process.env.STAGE_ENV || "development"
  }
```
Code
```
  const errorLink = onError(({ graphQLErrors, networkError, operation }) => {
    ctx.$sentry.withScope(scope => {
      try {
        scope.setTag("kind", operation.operationName);
        scope.setExtra("kind", operation.operationName);
        scope.setExtra("variables", operation.variables);
        scope.setExtra("query", operation.query);
      } catch (e) {
        // Do nothing
      }
      if (graphQLErrors) {
        graphQLErrors.forEach(e => {
          const error = new GraphQLRequestError(e.message);
          if (e.extensions) {
            scope.setExtra("code", e.extensions.code);
            if(e.extensions.exception) {
              scope.setExtra("exception", e.extensions.exception);
            } else {
              scope.setExtra("exception", e.message);
            }
          } else {
            scope.setExtra("code", null);
            scope.setExtra("exception", null);
          }
          ctx.$sentry.captureException(error);
        });
      } else if (networkError) {
        ctx.$sentry.captureException(networkError);
      }
    });
  });
```
Exception 
```{
    "errorType": "TypeError",
    "errorMessage": "ctx.$sentry.withScope is not a function",
    "stack": [
        "TypeError: ctx.$sentry.withScope is not a function",
        "    at server.js:1619:17",
        "    at Object.error (/var/task/node_modules/apollo-link-error/lib/index.js:33:41)",
        "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:140:18)",
        "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)",
        "    at SubscriptionObserver.error (/var/task/node_modules/zen-observable/lib/Observable.js:240:7)",
        "    at /var/task/node_modules/apollo-upload-client/lib/index.js:154:20",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

**Comment by rchl** [comment]
1. Is your project public so that I could look at other aspects of it?
2. Are you registering sentry module in `modules` array (rather than `buildModules`)?
3. When you say that it works when running locally do you mean when using `nuxt dev` or `nuxt build && nuxt start`? The latter should be used to make the environment as close to production as possible.
