### ISSUE TITLE
Nuxt build error when publishRelease enabled

### ISSUE THREAD

**Issue by kwolniak** [nuxt-community/sentry-module#460]
### Version
@nuxtjs/sentry: 6.0.1
nuxt: 2.15.8
webpack: 4.46.0

### Sentry configuration
```
sentry: {
    dsn: process.env.SENTRY_DSN,
    sourceMapStyle: 'hidden-source-map',
    publishRelease: {
       authToken: process.env.SENTRY_AUTH_TOKEN,
       org: 'my-org',
       project: 'my-project',
       // Attach commits to the release (requires that the build triggered within a git repository).
       setCommits: {
         auto: true,
       },
    },
},
```

### What is happening?

When I build my nuxt app with this config I got `Nuxt build error`. 
It is worth adding that in sentry.io, release is created and artifacts uploaded and associated to release during this failed build, but build is not finished and app is broken.

When I comment `sourceMapStyle` and `publishRelease` config, everything is working, sentry release is created and issues are assigned to this release but I don't have source-maps. 

Does anyone know what could be causing this or what I can check?

```
             img/icon.db03cfe.png    1.72 KiB                                                            [emitted] [immutable]
 + 88 hidden assets
Entrypoint app [big] = ec64575.js ec64575.js.map e7c6a7a.js e7c6a7a.js.map css/19b5178.css 2a5cb96.js 2a5cb96.js.map css/3dca577.css 4764608.js 4764608.js.map

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
...

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (1000 KiB). This can impact web performance.
Entrypoints:
...

 FATAL  Nuxt build error

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)

   ╭─────────────────────────────╮
   │                             
   │   ✖ Nuxt Fatal Error        
   │                             
   │   Error: Nuxt build error   
   │                             
   ╰─────────────────────────────╯

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ssh X@X.X.ovh "export NVM_DIR=\\"\\$HOME/.nvm\\"\n' +
    '[ -s \\"\\$NVM_DIR/nvm.sh\\" ] && \\. \\"\\$NVM_DIR/nvm.sh\\"\n' +
    '[ -s \\"\\$NVM_DIR/bash_completion\\" ] && \\. \\"\\$NVM_DIR/bash_completion\\" && cd /home/www/X/current && npm install && npm run-script build && pm2 startOrReload ecosystem.config.js --update-env"',

...

'\n' +
    '> X@1.0.0 build\n' +
    '> nuxt build\n' +
    '\n' +
    '✔ Sentry reporting is enabled (client side: enabled, server side: enabled)\n' +
    'ℹ Production build\n' +
    'ℹ Bundling for server and client side\n' +
    'ℹ Target: server\n' +
    'ℹ Using components loader to optimize imports\n' +
    'ℹ Discovered Components: .nuxt/components/readme.md\n' +
    '✔ Builder initialized\n' +
    '✔ Nuxt files generated\n' +
    'ℹ Compiling Client\n' +
    '✔ Client: Compiled successfully in X.95s\n' +
    'ℹ Compiling Server\n' +
    '> Found 164 release files\n' +
    '> Analyzing 164 sources\n' +
    '> Found 172 release files\n' +
    '> Analyzing 172 sources\n' +
    '> Rewriting sources\n' +
    '> Rewriting sources\n' +
    '> Adding source map references\n' +
    '> Adding source map references\n' +
    '> Bundled 164 files for upload\n' +
    '> Bundled 172 files for upload\n' +
    '> Uploaded release files to Sentry\n' +
    '> File upload complete (processing pending on server)\n' +
    '> Organization: X\n' +
    '> Project: X\n' +
    '> Release: XXXXXXX\n' +
    '> Dist: None\n' +
    '\n' +
    'Source Map Upload Report\n' +
    '  Scripts\n' +
...
```

**Comment by rchl** [comment]
I don't really know but this command looks suspicious:

```
  cmd: 'ssh X@X.X.ovh "export NVM_DIR=\\"\\$HOME/.nvm\\"\n' +
    '[ -s \\"\\$NVM_DIR/nvm.sh\\" ] && \\. \\"\\$NVM_DIR/nvm.sh\\"\n' +
    '[ -s \\"\\$NVM_DIR/bash_completion\\" ] && \\. \\"\\$NVM_DIR/bash_completion\\" && cd /home/www/X/current && npm install && npm run-script build && pm2 startOrReload ecosystem.config.js --update-env"',
```

What is trying to run this command? Is your default sheell doing that on being initialized? Seems kinda strange to start pm2 at this point maybe...

**Comment by kwolniak** [comment]
Deploy script run it on every application server.

So after code is copied to every application servers, script goes to current folder and install node dependencies, run build and reload pm2 to serve new app version to users.

When I remove `publishRelease` from sentry config deploy and build works without any problem, but of course I do not have assets (source-maps) uploaded to sentry.

**Comment by jslikai918** [comment]
hi, bro .
Are you resolve this problem?  I meet the same problem , and I don't know how to fix it
wish your reception

**Comment by rchl** [comment]
@kwolniak I wonder if there is something more in the output that was left out but could be helpful with analyzing it...

Basically all we see from it is that Nuxt crashed during build:

```
 FATAL  Nuxt build error

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
```

 but there is not enough info besides that to tell what's happening.

**Comment by rchl** [comment]
@jslikai918 what's the output you are getting during build? Paste as much as you can (redact private/sensitive stuff if there is any).

**Comment by jslikai918** [comment]
> @jslikai918你在构建过程中得到的输出是什么？尽可能多地粘贴（如果有的话，请编辑私人/敏感内容）。

<img width="915" alt="image" src="https://user-images.githubusercontent.com/116713358/207767144-bd9df2ed-de30-4120-9f98-c0e68dd8b564.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/116713358/207767206-c869aeaa-09c0-4ce8-8d6f-3c80868863b0.png">
You can see, I had config the org , but it still report error , it must build a .sentryclirc ? 
thank you

**Comment by rchl** [comment]
First of all, is not the same issue.

Second, where do you use those exported variables? Alle how your sentry module configuration look like.

Also make sure that you read module's documentation as it might have answer to your question already.

**Comment by jslikai918** [comment]
@rchl ok, I will read the documentation again, thanks

**Comment by rchl** [comment]
Any changes with the latest version of the module?

**Comment by rchl** [comment]
Closing due to lack of response. We can re-open if there is more info to work with.
